# Generated by Django 4.2.1 on 2024-02-07 19:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0017_alter_cue_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='can_be_assigned_weight_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='has_tempo_assigned',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('eccentric', 'Eccentric'), ('concentric', 'Concentric'), ('isometric', 'Isometric'), ('no_tempo', 'No Tempo'), ('cannot_be_assigned', 'Cannot Be Assigned A Tempo')], default='cannot_be_assigned', max_length=255),
        ),
    ]
