# Generated by Django 4.2.1 on 2024-02-07 19:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0019_alter_exercise_has_tempo_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='has_tempo_assigned',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('yes', 'Yes'), ('no_tempo', 'No'), ('cannot_be_assigned', 'Cannot be assigned a tempo')], default='cannot_be_assigned', max_length=255),
        ),
    ]
