# Generated by Django 4.2.1 on 2024-02-07 20:51

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0021_alter_exercise_has_tempo_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='has_tempo_assigned',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('yes', 'Tempo has been assigned already'), ('no_tempo', 'Not assigned yet'), ('cannot_be_assigned', 'Cannot be assigned a tempo')], max_length=255),
        ),
    ]
